#!/bin/bash

# Set up the database connection
export PGPORT=5432
export PGHOST="${POSTGRES_HOST}"
export PGDATABASE="${DATABASE_NAME}"
export PGUSER="${ADMIN_USER}"
export PGPASSWORD="${ADMIN_PASSWORD}"

# Create user and grant permissions
SQL_COMMAND="
CREATE USER ${USER} WITH PASSWORD '${PASSWORD}';
GRANT CONNECT ON DATABASE ${PGDATABASE} TO ${USER};
GRANT USAGE ON SCHEMA public TO ${USER};
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO ${USER};
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO ${USER};
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO ${USER};
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO ${USER};
"

# Run query
psql -c "${SQL_COMMAND}